"""add_form_layout_to_archive_category

Revision ID: 8d6c05abf461
Revises: 4ffd6fce0bcf
Create Date: 2026-04-23 20:00:08.767799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d6c05abf461'
down_revision: Union[str, Sequence[str], None] = '4ffd6fce0bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_archive_category', sa.Column('form_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='表单排版定义 FormLayout（行列布局）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_archive_category', 'form_layout')
    # ### end Alembic commands ###
