"""add_sys_dict_tables

Revision ID: eceabc81e6a9
Revises: 8d6c05abf461
Create Date: 2026-04-23 20:35:22.206370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eceabc81e6a9'
down_revision: Union[str, Sequence[str], None] = '8d6c05abf461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dict',
    sa.Column('dict_type', sa.String(length=64), nullable=False, comment='字典类型代码，全局唯一，如 MJ / BGQX'),
    sa.Column('dict_name', sa.String(length=100), nullable=False, comment='字典中文名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('is_builtin', sa.Boolean(), server_default='false', nullable=False, comment='是否系统内置（内置字典不可删除）'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序号（升序）'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_type')
    )
    op.create_table('sys_dict_item',
    sa.Column('dict_type', sa.String(length=64), nullable=False, comment='所属字典类型代码'),
    sa.Column('item_value', sa.String(length=200), nullable=False, comment='存储值（也是 select options 的 value）'),
    sa.Column('item_label', sa.String(length=200), nullable=False, comment='显示标签'),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='是否默认选中'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序号（升序）'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['dict_type'], ['sys_dict.dict_type'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dict_item_dict_type'), 'sys_dict_item', ['dict_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_dict_item_dict_type'), table_name='sys_dict_item')
    op.drop_table('sys_dict_item')
    op.drop_table('sys_dict')
    # ### end Alembic commands ###
