"""Add platform management models

Revision ID: 88efb021a904
Revises: f13215c41b5d
Create Date: 2026-02-23 10:23:33.209849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88efb021a904'
down_revision: Union[str, Sequence[str], None] = 'f13215c41b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iam_menu',
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父级菜单/权限ID'),
    sa.Column('code', sa.String(length=100), nullable=False, comment="权限/菜单编码, 例如'system:user:add'"),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型: DIR(目录) MENU(菜单) BUTTON(按钮/权限)'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路由路径 (仅菜单)'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_visible', sa.Boolean(), nullable=False, comment='是否可见'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['iam_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iam_menu_code'), 'iam_menu', ['code'], unique=True)
    op.create_index(op.f('ix_iam_menu_parent_id'), 'iam_menu', ['parent_id'], unique=False)
    op.create_table('iam_tenant',
    sa.Column('code', sa.String(length=50), nullable=False, comment='租户编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='租户描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iam_tenant_code'), 'iam_tenant', ['code'], unique=True)
    op.create_table('iam_organization',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='所属租户ID'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父组织ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组织名称'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='组织编码'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['iam_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iam_organization_code'), 'iam_organization', ['code'], unique=False)
    op.create_index(op.f('ix_iam_organization_parent_id'), 'iam_organization', ['parent_id'], unique=False)
    op.create_index(op.f('ix_iam_organization_tenant_id'), 'iam_organization', ['tenant_id'], unique=False)
    op.create_table('iam_role_menu',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['iam_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['iam_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('iam_audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='操作用户ID'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="操作动作 (例如: 'USER_LOGIN', 'DELETE_ARCHIVE')"),
    sa.Column('module', sa.String(length=50), nullable=False, comment="功能模块 (例如: 'IAM', 'ARCHIVE')"),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='用户代理解析'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: SUCCESS, FAILED'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='结构化操作详情 (JSON)'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['iam_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iam_audit_log_action'), 'iam_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_iam_audit_log_module'), 'iam_audit_log', ['module'], unique=False)
    op.create_index(op.f('ix_iam_audit_log_tenant_id'), 'iam_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_iam_audit_log_user_id'), 'iam_audit_log', ['user_id'], unique=False)
    op.add_column('iam_role', sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户ID (空为全局)'))
    op.create_index(op.f('ix_iam_role_tenant_id'), 'iam_role', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'iam_role', 'iam_tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('iam_user', sa.Column('org_id', sa.UUID(), nullable=True, comment='所属组织ID'))
    op.execute("UPDATE iam_user SET tenant_id = NULL")
    op.alter_column('iam_user', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.UUID(),
               comment='所属租户ID',
               existing_comment='租户ID (Bureau/Archive/Office)',
               existing_nullable=True,
               postgresql_using='tenant_id::uuid')
    op.create_index(op.f('ix_iam_user_org_id'), 'iam_user', ['org_id'], unique=False)
    op.create_foreign_key(None, 'iam_user', 'iam_organization', ['org_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'iam_user', 'iam_tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'iam_user', type_='foreignkey')
    op.drop_constraint(None, 'iam_user', type_='foreignkey')
    op.drop_index(op.f('ix_iam_user_org_id'), table_name='iam_user')
    op.alter_column('iam_user', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=50),
               comment='租户ID (Bureau/Archive/Office)',
               existing_comment='所属租户ID',
               existing_nullable=True)
    op.drop_column('iam_user', 'org_id')
    op.drop_constraint(None, 'iam_role', type_='foreignkey')
    op.drop_index(op.f('ix_iam_role_tenant_id'), table_name='iam_role')
    op.drop_column('iam_role', 'tenant_id')
    op.drop_index(op.f('ix_iam_audit_log_user_id'), table_name='iam_audit_log')
    op.drop_index(op.f('ix_iam_audit_log_tenant_id'), table_name='iam_audit_log')
    op.drop_index(op.f('ix_iam_audit_log_module'), table_name='iam_audit_log')
    op.drop_index(op.f('ix_iam_audit_log_action'), table_name='iam_audit_log')
    op.drop_table('iam_audit_log')
    op.drop_table('iam_role_menu')
    op.drop_index(op.f('ix_iam_organization_tenant_id'), table_name='iam_organization')
    op.drop_index(op.f('ix_iam_organization_parent_id'), table_name='iam_organization')
    op.drop_index(op.f('ix_iam_organization_code'), table_name='iam_organization')
    op.drop_table('iam_organization')
    op.drop_index(op.f('ix_iam_tenant_code'), table_name='iam_tenant')
    op.drop_table('iam_tenant')
    op.drop_index(op.f('ix_iam_menu_parent_id'), table_name='iam_menu')
    op.drop_index(op.f('ix_iam_menu_code'), table_name='iam_menu')
    op.drop_table('iam_menu')
    # ### end Alembic commands ###
