"""Add user profile fields

Revision ID: 5ef77622c1c5
Revises: 88efb021a904
Create Date: 2026-02-26 22:08:09.907606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef77622c1c5'
down_revision: Union[str, Sequence[str], None] = '88efb021a904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iam_user', sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'))
    op.add_column('iam_user', sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'))
    op.add_column('iam_user', sa.Column('job_title', sa.String(length=100), nullable=True, comment='职位'))
    op.add_column('iam_user', sa.Column('location', sa.String(length=100), nullable=True, comment='办公地点'))
    op.add_column('iam_user', sa.Column('bio', sa.String(length=500), nullable=True, comment='个人简介'))
    op.add_column('iam_user', sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iam_user', 'last_login_time')
    op.drop_column('iam_user', 'bio')
    op.drop_column('iam_user', 'location')
    op.drop_column('iam_user', 'job_title')
    op.drop_column('iam_user', 'phone')
    op.drop_column('iam_user', 'avatar')
    # ### end Alembic commands ###
