"""archive_no_rule_engine

Revision ID: cadddbb0fa28
Revises: 2a6b72efc717
Create Date: 2026-04-19 20:27:39.899407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cadddbb0fa28'
down_revision: Union[str, Sequence[str], None] = '2a6b72efc717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_archive_no_seq',
    sa.Column('rule_id', sa.UUID(), nullable=False, comment='所属规则'),
    sa.Column('scope_key', sa.String(length=200), nullable=False, comment='序号范围键，如 catalog_year:<catalog_id>:<year>'),
    sa.Column('current_seq', sa.Integer(), nullable=False, comment='当前已分配的最大序号'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['rule_id'], ['repo_archive_no_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'scope_key', name='uq_no_seq_rule_scope')
    )
    op.create_index(op.f('ix_repo_archive_no_seq_rule_id'), 'repo_archive_no_seq', ['rule_id'], unique=False)
    # Note: GIN index on ext_fields and composite index on (fonds_id, catalog_id, year)
    # were created manually in migration 2a6b72efc717 — keep them, do not drop.
    op.add_column('repo_archive_category', sa.Column('archive_no_rule_id', sa.UUID(), nullable=True, comment='激活的档号规则（NULL 表示不自动生成）'))
    op.alter_column('repo_archive_category', 'field_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='字段定义列表 list[FieldDefinition]',
               existing_comment='字段定义列表：[{name,label,type,required,options,...}]',
               existing_nullable=True)
    op.create_foreign_key(
        'fk_archive_category_no_rule_id',
        'repo_archive_category', 'repo_archive_no_rule',
        ['archive_no_rule_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_archive_category_no_rule_id', 'repo_archive_category', type_='foreignkey')
    op.alter_column('repo_archive_category', 'field_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment='字段定义列表：[{name,label,type,required,options,...}]',
               existing_comment='字段定义列表 list[FieldDefinition]',
               existing_nullable=True)
    op.drop_column('repo_archive_category', 'archive_no_rule_id')
    # GIN and composite indexes were created manually in 2a6b72efc717 — no need to recreate on downgrade.
    op.drop_index(op.f('ix_repo_archive_no_seq_rule_id'), table_name='repo_archive_no_seq')
    op.drop_table('repo_archive_no_seq')
    # ### end Alembic commands ###
