"""Add schedule models

Revision ID: b9d297427344
Revises: 5ef77622c1c5
Create Date: 2026-03-20 16:15:27.603084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d297427344'
down_revision: Union[str, Sequence[str], None] = '5ef77622c1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_events',
    sa.Column('title', sa.String(length=255), nullable=False, comment='日程标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='日程描述'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='结束时间'),
    sa.Column('is_all_day', sa.Boolean(), nullable=False, comment='是否全天'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='地点'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='日程类型'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户ID'),
    sa.Column('creator_id', sa.UUID(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['creator_id'], ['iam_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_events_creator_id'), 'schedule_events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_schedule_events_tenant_id'), 'schedule_events', ['tenant_id'], unique=False)
    op.create_table('schedule_participants',
    sa.Column('event_id', sa.UUID(), nullable=False, comment='日程ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='参与状态: pending, accepted, declined'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['iam_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_participants_event_id'), 'schedule_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_schedule_participants_user_id'), 'schedule_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_participants_user_id'), table_name='schedule_participants')
    op.drop_index(op.f('ix_schedule_participants_event_id'), table_name='schedule_participants')
    op.drop_table('schedule_participants')
    op.drop_index(op.f('ix_schedule_events_tenant_id'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_creator_id'), table_name='schedule_events')
    op.drop_table('schedule_events')
    # ### end Alembic commands ###
