"""add sys_notification table

Revision ID: f13215c41b5d
Revises: 53e83c27d970
Create Date: 2026-02-22 22:12:30.984398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13215c41b5d'
down_revision: Union[str, Sequence[str], None] = '53e83c27d970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_notification',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='接收用户ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='正文内容'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型: system / todo / message'),
    sa.Column('level', sa.String(length=20), server_default='info', nullable=False, comment='级别: info / warning / error'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='是否已读'),
    sa.Column('read_time', sa.DateTime(timezone=True), nullable=True, comment='已读时间'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='来源模块, 如 archive, workflow'),
    sa.Column('source_id', sa.String(length=50), nullable=True, comment='来源对象ID'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['user_id'], ['iam_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_notification_type'), 'sys_notification', ['type'], unique=False)
    op.create_index(op.f('ix_sys_notification_user_id'), 'sys_notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_notification_user_id'), table_name='sys_notification')
    op.drop_index(op.f('ix_sys_notification_type'), table_name='sys_notification')
    op.drop_table('sys_notification')
    # ### end Alembic commands ###
