"""batch_import_tables

Revision ID: 4ffd6fce0bcf
Revises: cadddbb0fa28
Create Date: 2026-04-20 21:10:28.542724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ffd6fce0bcf'
down_revision: Union[str, Sequence[str], None] = 'cadddbb0fa28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_field_mapping_template',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='所属门类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="映射列表 [{source_col: '文件题名', target_field: 'title'}, ...]"),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='是否为该门类的默认映射模板'),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['category_id'], ['repo_archive_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_field_mapping_template_category_id'), 'repo_field_mapping_template', ['category_id'], unique=False)
    op.create_index(op.f('ix_repo_field_mapping_template_tenant_id'), 'repo_field_mapping_template', ['tenant_id'], unique=False)
    op.create_table('repo_import_task',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='导入的档案门类'),
    sa.Column('fonds_id', sa.UUID(), nullable=False, comment='目标全宗'),
    sa.Column('catalog_id', sa.UUID(), nullable=False, comment='目标目录'),
    sa.Column('operator_id', sa.UUID(), nullable=False, comment='操作人'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态: pending/running/done/failed'),
    sa.Column('file_key', sa.String(length=1024), nullable=True, comment='上传的原始文件对象键'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('mapping_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='本次导入使用的字段映射快照'),
    sa.Column('total', sa.Integer(), nullable=False, comment='总行数'),
    sa.Column('success', sa.Integer(), nullable=False, comment='成功行数'),
    sa.Column('failed', sa.Integer(), nullable=False, comment='失败行数'),
    sa.Column('skipped', sa.Integer(), nullable=False, comment='跳过行数'),
    sa.Column('error_report_key', sa.String(length=1024), nullable=True, comment='失败报表文件的对象键'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='任务开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成时间'),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['catalog_id'], ['repo_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['repo_archive_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fonds_id'], ['repo_fonds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['iam_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_import_task_catalog_id'), 'repo_import_task', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_repo_import_task_category_id'), 'repo_import_task', ['category_id'], unique=False)
    op.create_index(op.f('ix_repo_import_task_fonds_id'), 'repo_import_task', ['fonds_id'], unique=False)
    op.create_index(op.f('ix_repo_import_task_tenant_id'), 'repo_import_task', ['tenant_id'], unique=False)
    op.alter_column('repo_archive_no_rule', 'rule_template',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='规则段定义（见 docs/features/feature_档案管理.md 第五章）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repo_archive_no_rule', 'rule_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='规则段定义（见 docs/features/feature_档案管理.md 第五章）',
               existing_nullable=True)
    op.drop_index(op.f('ix_repo_import_task_tenant_id'), table_name='repo_import_task')
    op.drop_index(op.f('ix_repo_import_task_fonds_id'), table_name='repo_import_task')
    op.drop_index(op.f('ix_repo_import_task_category_id'), table_name='repo_import_task')
    op.drop_index(op.f('ix_repo_import_task_catalog_id'), table_name='repo_import_task')
    op.drop_table('repo_import_task')
    op.drop_index(op.f('ix_repo_field_mapping_template_tenant_id'), table_name='repo_field_mapping_template')
    op.drop_index(op.f('ix_repo_field_mapping_template_category_id'), table_name='repo_field_mapping_template')
    op.drop_table('repo_field_mapping_template')
    # ### end Alembic commands ###
