"""archive_management_foundation

Revision ID: 2a6b72efc717
Revises: f19ee582a1e1
Create Date: 2026-04-19 16:59:38.629374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a6b72efc717'
down_revision: Union[str, Sequence[str], None] = 'f19ee582a1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_archive_category',
    sa.Column('code', sa.String(length=20), nullable=False, comment='门类代码，如 WS/KJ/HJ'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='门类名称'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父门类（专业档案子门类使用）'),
    sa.Column('base_category_id', sa.UUID(), nullable=True, comment='克隆来源（自定义门类）'),
    sa.Column('is_builtin', sa.Boolean(), server_default='false', nullable=False, comment='是否内置 DA/T 标准门类'),
    sa.Column('requires_privacy_guard', sa.Boolean(), server_default='false', nullable=False, comment='是否含个人隐私字段（专业档案）'),
    sa.Column('field_schema', sa.JSON(), nullable=True, comment='字段定义列表：[{name,label,type,required,options,...}]'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户（NULL=系统内置）'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['base_category_id'], ['repo_archive_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['repo_archive_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_repo_archive_category_tenant_id'), 'repo_archive_category', ['tenant_id'], unique=False)
    op.create_table('repo_archive_no_rule',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='所属门类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('rule_template', sa.JSON(), nullable=True, comment='规则段定义（见 docs/features/feature_档案管理.md 第五章）'),
    sa.Column('seq_scope', sa.String(length=20), nullable=False, comment='序号重置范围: catalog | catalog_year | fonds'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['category_id'], ['repo_archive_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_archive_no_rule_category_id'), 'repo_archive_no_rule', ['category_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_no_rule_tenant_id'), 'repo_archive_no_rule', ['tenant_id'], unique=False)
    op.create_table('repo_catalog',
    sa.Column('fonds_id', sa.UUID(), nullable=False, comment='所属全宗'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='对应门类'),
    sa.Column('catalog_no', sa.String(length=50), nullable=False, comment='目录号，同全宗内唯一'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='目录名称'),
    sa.Column('year', sa.Integer(), nullable=True, comment='年度'),
    sa.Column('org_mode', sa.String(length=20), nullable=False, comment='整理方式: by_item（一文一件）| by_volume（案卷卷内）'),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['category_id'], ['repo_archive_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fonds_id'], ['repo_fonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_catalog_fonds_id'), 'repo_catalog', ['fonds_id'], unique=False)
    op.create_index(op.f('ix_repo_catalog_tenant_id'), 'repo_catalog', ['tenant_id'], unique=False)
    op.create_table('repo_archive',
    sa.Column('fonds_id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='NULL=顶级，有值=卷内文件'),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False, comment='volume | item'),
    sa.Column('archive_no', sa.String(length=100), nullable=True, comment='档号（生成结果，可手动覆盖）'),
    sa.Column('fonds_code', sa.String(length=50), nullable=False, comment='全宗号'),
    sa.Column('catalog_no', sa.String(length=50), nullable=True, comment='目录号'),
    sa.Column('volume_no', sa.String(length=50), nullable=True, comment='案卷号（一文一件时为空）'),
    sa.Column('item_no', sa.String(length=50), nullable=True, comment='件号'),
    sa.Column('year', sa.Integer(), nullable=True, comment='年度'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='题名'),
    sa.Column('creator', sa.String(length=200), nullable=True, comment='责任者'),
    sa.Column('security_level', sa.String(length=20), nullable=False, comment='密级: public | internal | confidential | secret'),
    sa.Column('retention_period', sa.String(length=20), nullable=False, comment='保管期限: permanent | long | short'),
    sa.Column('doc_date', sa.String(length=20), nullable=True, comment='文件日期 YYYY-MM-DD'),
    sa.Column('pages', sa.Integer(), nullable=True, comment='页数'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | restricted | destroyed'),
    sa.Column('ext_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='门类私有字段（GIN 索引）'),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), nullable=False, comment='ES/向量化状态: pending | processing | done | failed'),
    sa.Column('es_synced_at', sa.String(length=30), nullable=True, comment='最后成功同步 ES 的时间 ISO8601'),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['catalog_id'], ['repo_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['repo_archive_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fonds_id'], ['repo_fonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['repo_archive.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_archive_archive_no'), 'repo_archive', ['archive_no'], unique=False)
    op.create_index(op.f('ix_repo_archive_catalog_id'), 'repo_archive', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_category_id'), 'repo_archive', ['category_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_creator'), 'repo_archive', ['creator'], unique=False)
    op.create_index(op.f('ix_repo_archive_fonds_code'), 'repo_archive', ['fonds_code'], unique=False)
    op.create_index(op.f('ix_repo_archive_fonds_id'), 'repo_archive', ['fonds_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_parent_id'), 'repo_archive', ['parent_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_tenant_id'), 'repo_archive', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_title'), 'repo_archive', ['title'], unique=False)
    op.create_index(op.f('ix_repo_archive_year'), 'repo_archive', ['year'], unique=False)
    # 先删 item（依赖 file），再删 file
    op.drop_index(op.f('ix_repo_archive_item_archive_file_id'), table_name='repo_archive_item')
    op.drop_index(op.f('ix_repo_archive_item_tenant_id'), table_name='repo_archive_item')
    op.drop_table('repo_archive_item')
    op.drop_index(op.f('ix_repo_archive_file_fonds_id'), table_name='repo_archive_file')
    op.drop_index(op.f('ix_repo_archive_file_tenant_id'), table_name='repo_archive_file')
    op.drop_index(op.f('ix_repo_archive_file_year'), table_name='repo_archive_file')
    op.drop_table('repo_archive_file')
    # GIN 索引（autogenerate 不自动生成）
    op.execute("CREATE INDEX IF NOT EXISTS ix_repo_archive_ext_fields_gin ON repo_archive USING GIN (ext_fields jsonb_path_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_repo_archive_fonds_catalog_year ON repo_archive (fonds_id, catalog_id, year)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_archive_item',
    sa.Column('archive_file_id', sa.UUID(), autoincrement=False, nullable=False, comment='所属案卷'),
    sa.Column('item_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='文件号（案卷内序号）'),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False, comment='文件题名'),
    sa.Column('item_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='文件类型'),
    sa.Column('author', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='责任者（作者/发文机关）'),
    sa.Column('document_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='文件日期（YYYY-MM-DD）'),
    sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True, comment='页数'),
    sa.Column('security_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='密级'),
    sa.Column('storage_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True, comment='对象存储键（MinIO/S3 object key）'),
    sa.Column('storage_bucket', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='存储桶名'),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True, comment='文件大小（字节）'),
    sa.Column('file_format', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='文件格式，如 pdf/docx/tiff'),
    sa.Column('sha256_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='SHA-256 哈希值'),
    sa.Column('embedding_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='向量化状态: pending/processing/done/failed'),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True, comment='所属租户'),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='扩展元数据（原文件头信息等）'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='唯一标识'),
    sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['archive_file_id'], ['repo_archive_file.id'], name=op.f('repo_archive_item_archive_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], name=op.f('repo_archive_item_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('repo_archive_item_pkey'))
    )
    op.create_index(op.f('ix_repo_archive_item_tenant_id'), 'repo_archive_item', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_item_archive_file_id'), 'repo_archive_item', ['archive_file_id'], unique=False)
    op.create_table('repo_archive_file',
    sa.Column('fonds_id', sa.UUID(), autoincrement=False, nullable=False, comment='所属全宗'),
    sa.Column('file_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='案卷号（同一全宗内唯一）'),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False, comment='案卷题名'),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True, comment='形成年度'),
    sa.Column('classification', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='分类（科目）'),
    sa.Column('retention_period', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='保管期限'),
    sa.Column('security_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='密级：public/internal/confidential/secret'),
    sa.Column('item_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='文件条目数'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='案卷状态'),
    sa.Column('source_sip_id', sa.UUID(), autoincrement=False, nullable=True, comment='来源SIP包ID'),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True, comment='所属租户'),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='扩展元数据'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='唯一标识'),
    sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), autoincrement=False, nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['fonds_id'], ['repo_fonds.id'], name=op.f('repo_archive_file_fonds_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_sip_id'], ['col_sip_record.id'], name=op.f('repo_archive_file_source_sip_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], name=op.f('repo_archive_file_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('repo_archive_file_pkey'))
    )
    op.create_index(op.f('ix_repo_archive_file_year'), 'repo_archive_file', ['year'], unique=False)
    op.create_index(op.f('ix_repo_archive_file_tenant_id'), 'repo_archive_file', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_file_fonds_id'), 'repo_archive_file', ['fonds_id'], unique=False)
    op.execute("DROP INDEX IF EXISTS ix_repo_archive_ext_fields_gin")
    op.execute("DROP INDEX IF EXISTS ix_repo_archive_fonds_catalog_year")
    op.drop_index(op.f('ix_repo_archive_year'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_title'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_tenant_id'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_parent_id'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_fonds_id'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_fonds_code'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_creator'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_category_id'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_catalog_id'), table_name='repo_archive')
    op.drop_index(op.f('ix_repo_archive_archive_no'), table_name='repo_archive')
    op.drop_table('repo_archive')
    op.drop_index(op.f('ix_repo_catalog_tenant_id'), table_name='repo_catalog')
    op.drop_index(op.f('ix_repo_catalog_fonds_id'), table_name='repo_catalog')
    op.drop_table('repo_catalog')
    op.drop_index(op.f('ix_repo_archive_no_rule_tenant_id'), table_name='repo_archive_no_rule')
    op.drop_index(op.f('ix_repo_archive_no_rule_category_id'), table_name='repo_archive_no_rule')
    op.drop_table('repo_archive_no_rule')
    op.drop_index(op.f('ix_repo_archive_category_tenant_id'), table_name='repo_archive_category')
    op.drop_table('repo_archive_category')
    # ### end Alembic commands ###
