"""add_is_system_to_menu_and_role

Revision ID: f19ee582a1e1
Revises: d5e2b8a91c34
Create Date: 2026-04-12 21:07:57.374220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19ee582a1e1'
down_revision: Union[str, Sequence[str], None] = 'd5e2b8a91c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_fonds',
    sa.Column('fonds_code', sa.String(length=50), nullable=False, comment='全宗号（全国唯一）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='全宗名称（机构全称）'),
    sa.Column('short_name', sa.String(length=100), nullable=True, comment='全宗简称'),
    sa.Column('description', sa.Text(), nullable=True, comment='全宗说明'),
    sa.Column('start_year', sa.Integer(), nullable=True, comment='起始年度'),
    sa.Column('end_year', sa.Integer(), nullable=True, comment='截止年度（现存全宗为空）'),
    sa.Column('retention_period', sa.String(length=20), nullable=False, comment='保管期限'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='全宗状态'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户'),
    sa.Column('custodian_id', sa.UUID(), nullable=True, comment='责任保管人'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['custodian_id'], ['iam_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_fonds_fonds_code'), 'repo_fonds', ['fonds_code'], unique=True)
    op.create_index(op.f('ix_repo_fonds_tenant_id'), 'repo_fonds', ['tenant_id'], unique=False)
    op.create_table('repo_archive_file',
    sa.Column('fonds_id', sa.UUID(), nullable=False, comment='所属全宗'),
    sa.Column('file_number', sa.String(length=100), nullable=False, comment='案卷号（同一全宗内唯一）'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='案卷题名'),
    sa.Column('year', sa.Integer(), nullable=True, comment='形成年度'),
    sa.Column('classification', sa.String(length=100), nullable=True, comment='分类（科目）'),
    sa.Column('retention_period', sa.String(length=20), nullable=False, comment='保管期限'),
    sa.Column('security_level', sa.String(length=20), nullable=False, comment='密级：public/internal/confidential/secret'),
    sa.Column('item_count', sa.Integer(), nullable=False, comment='文件条目数'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='案卷状态'),
    sa.Column('source_sip_id', sa.UUID(), nullable=True, comment='来源SIP包ID'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['fonds_id'], ['repo_fonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_sip_id'], ['col_sip_record.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_archive_file_fonds_id'), 'repo_archive_file', ['fonds_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_file_tenant_id'), 'repo_archive_file', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_file_year'), 'repo_archive_file', ['year'], unique=False)
    op.create_table('repo_archive_item',
    sa.Column('archive_file_id', sa.UUID(), nullable=False, comment='所属案卷'),
    sa.Column('item_number', sa.String(length=100), nullable=False, comment='文件号（案卷内序号）'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='文件题名'),
    sa.Column('item_type', sa.String(length=30), nullable=False, comment='文件类型'),
    sa.Column('author', sa.String(length=200), nullable=True, comment='责任者（作者/发文机关）'),
    sa.Column('document_date', sa.String(length=20), nullable=True, comment='文件日期（YYYY-MM-DD）'),
    sa.Column('pages', sa.Integer(), nullable=True, comment='页数'),
    sa.Column('security_level', sa.String(length=20), nullable=False, comment='密级'),
    sa.Column('storage_key', sa.String(length=1024), nullable=True, comment='对象存储键（MinIO/S3 object key）'),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True, comment='存储桶名'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('file_format', sa.String(length=50), nullable=True, comment='文件格式，如 pdf/docx/tiff'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True, comment='SHA-256 哈希值'),
    sa.Column('embedding_status', sa.String(length=20), nullable=False, comment='向量化状态: pending/processing/done/failed'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='所属租户'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='扩展元数据（原文件头信息等）'),
    sa.Column('id', sa.UUID(), nullable=False, comment='唯一标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否逻辑删除'),
    sa.ForeignKeyConstraint(['archive_file_id'], ['repo_archive_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['iam_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_archive_item_archive_file_id'), 'repo_archive_item', ['archive_file_id'], unique=False)
    op.create_index(op.f('ix_repo_archive_item_tenant_id'), 'repo_archive_item', ['tenant_id'], unique=False)
    op.add_column('iam_menu', sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='系统内置菜单，不可删除'))
    op.add_column('iam_role', sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='系统内置角色，不可删除'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iam_role', 'is_system')
    op.drop_column('iam_menu', 'is_system')
    op.drop_index(op.f('ix_repo_archive_item_tenant_id'), table_name='repo_archive_item')
    op.drop_index(op.f('ix_repo_archive_item_archive_file_id'), table_name='repo_archive_item')
    op.drop_table('repo_archive_item')
    op.drop_index(op.f('ix_repo_archive_file_year'), table_name='repo_archive_file')
    op.drop_index(op.f('ix_repo_archive_file_tenant_id'), table_name='repo_archive_file')
    op.drop_index(op.f('ix_repo_archive_file_fonds_id'), table_name='repo_archive_file')
    op.drop_table('repo_archive_file')
    op.drop_index(op.f('ix_repo_fonds_tenant_id'), table_name='repo_fonds')
    op.drop_index(op.f('ix_repo_fonds_fonds_code'), table_name='repo_fonds')
    op.drop_table('repo_fonds')
    # ### end Alembic commands ###
